#!/usr/bin/env bash
# Creates the file /var/run/my_process.pid


echo "$$" > /var/run/my_process.pid
trap "echo 'manage_my_process started'; rm /var/run/my_process.pid; exit" SIGTERM
trap "rm /var/run/manage_my_process.pid; exit" SIGQUIT
trap "manage_my_process restarted'" SIGINT
while true; do
      echo " I am alive!"
      sleep 2
done
